config/routes.rb
Rails.application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  devise_for :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
  root "articles#index"

  resources :articles do
    resources :comments, shallow: true
    get "publish"
  end
end

app/models/ability.rb
# frozen_string_literal: true

class Ability
  include CanCan::Ability
  def initialize(user)
    can :read, Article

    return unless user.present?

    can [:create, :update, :delete], Article, user: user

    can :create, Comment

    can :destroy, Comment do |comment|
      comment.article.user == user
    end

    return unless user.admin?

    can :manage, :all
  end
end

app/models/admin_user.rb
class AdminUser < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/article.rb
class Article < ApplicationRecord
  belongs_to :user 
  has_many :comments, dependent: :destroy
  belongs_to :user

  validates :title, presence: true
  validates :body, presence: true, length: { minimum: 10}
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :article

  validates :comment, presence: true, length: { minimum: 10 }
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
	before_action :authenticate_user!
	include Pundit::Authorization	
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController

  def index
    @articles = policy_scope(Article)
  end

  def show
    @article = Article.find(params[:id])

    if params.has_key?(:comment)
      @comment = Comment.new(comment: params[:comment], commenter: params[:commenter], article_id: params[:id])
      else
      @comment = Comment.new(article_id: params[:id])
    end
  end
  def new
    @article = Article.new
  end

  def create
    @article = Article.new(article_params.merge(user_id: current_user.id))
    
    if @article.save
      redirect_to(@article)
    else

      render :new, status: :unprocessable_entity
    end
  end

  def edit
    @article = Article.find(params[:id])
  end

  def update
    debugger
    @article = Article.find(params[:id])

    if @article.update(article_params)
      redirect_to(@article)
    else

      render :new, status: :unprocessable_entity
    end
  end

  def destroy
    @article = Article.find(params[:id])
    authorize @article
    @article.destroy

    redirect_to root_path, status: :see_other
  end

  def publish
    debugger
    @article = Article.find(params[:article_id])
    @article.update!(published: true)
    flash[notice] = "Article has been published successfully"
    redirect_to articles_path
  end

  private

  def article_params
    params.require(:article).permit(:title, :body, :published)
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  load_and_authorize_resource

  def create
    @comment = Comment.new(comment_params.merge(article_id: params[:article_id], commenter: current_user.email))
    @article = Article.find(params[:article_id])

    if @comment.save

      redirect_to @article
    else

      redirect_to article_path(@article, comment_show_params)
    end
  end

  def destroy
    @comment = Comment.find(params[:id])
    @comment.destroy

    redirect_to article_path(@comment.article), status: :see_other
  end

  private
  def comment_params
    params.require(:comment).permit(:comment, :article_id)
  end

  def comment_show_params
    {
      comment: @comment.comment,
      comment_err: @comment.errors.full_messages_for(:comment).first    }
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/auth_helper.rb
module AuthHelper
end

app/views/articles/_articles.erb
<table>
	<tr>
		<th>Article</th>
		<th>Commenter</th>
		<th>Comment</th>
	</tr>

	<% articles.each do |article| %>
		<% article.comments.each do |comment| %>
				<tr>
					<td><%= article.title %><td>
					<td><%= comment.commenter%></td>
					<td><%= comment.comment %></td>
				</tr>
		<% end %>
	<% end %>
</table>

app/views/articles/_form.html.erb
<%= form_with model: @article do |form| %>
  <div>
    <%= form.label :title %> <br>
    <%= form.text_field :title %>

    <% @article.errors.full_messages_for(:title).each do |message|%>
      <div><%= message %></div>
    <% end %>
  </div>

  <div>
    <%= form.label :body %> <br>
    <%= form.text_field :body %>

    <% @article.errors.full_messages_for(:body).each do |message|%>
      <div><%= message %></div>
    <% end %>
  </div>

  <div>
    <%= form.label :published, "Publish now" %>
    <%= form.check_box :published %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/articles/edit.html.erb
<h1>Edit Article</h1>

<%= render "form" %>

app/views/articles/index.html.erb
<h1>List of Available Articles</h1>

<table>
  <tr>
    <th> <%= "Title".ljust(20) %> </th>
    <th> <%= "Author".ljust(20) %> </th>
    <th> <%= "Status".ljust(20) %> </th>
    <th> <%= "Change Status".ljust(20) %> </th>
    <th> <%= "Remove Article" %> </th>
  </tr>

  <% @articles.each do |article| %>
  <tr>
    <td><%= link_to article.title, article %></td>
    <td>&nbsp <%= User.find(article.user_id).email %></td>

    <td>
      <% if article.published %>
        Published
      <% else %>
        Not Published
      <% end %>
    </td>

    <td>
      <% unless article.published %>
        <%= link_to "Publish Now", article_publish_url(article.id)%>
      <% end %>
    </td>

    <td>
      <% if policy(article).destroy? %>
        <%= button_to "Delete", article, method: :delete %>
      <% end %>
    </td>

  </tr>
  <% end %>

</table>
<br>
<%= link_to "Create New Article", new_article_path %>

app/views/articles/new.html.erb
<h1>Create New Article</h1>

<%= render "form" %>

app/views/articles/show.html.erb
<%= current_user.name %>
<% if current_user.admin? %>
  <p>Admin</p>
<% end %>

<div>
  <p><strong>Title: </strong><%= @article.title %></p>
  <p><strong>Body: </strong> <%= @article.body %></p>

</div>

<% if policy(@article).update? %>
  <%= link_to "Edit", edit_article_path(@article) %>
<% end %>

<% if policy(@article).destroy? %>
  <%= button_to "Delete", @article, method: :delete %>
<%end%>

<h3>Comments on the article</h3>
<%= render @article.comments %>

<h3> Add a Comment </h3>
<%= render "comments/form", comment: @comment %>

app/views/comments/_comment.html.erb
	<ul>
    <li>Commenter: <%= comment.commenter %> </li>
    <li>Comment: <%= comment.comment %> </li>
  </ul>

  <%= button_to "Delete Comment", comment_path(comment.id,), method: :delete %>

app/views/comments/_form.html.erb
<%= form_with model: [@article, @comment] do |form| %>
  <div>
    <%= form.label :comment %><br>
    <%= form.text_area :comment %>

		<div> <%= params[:comment_err] %> </div>
	</div>

	<div>
    <%= form.submit %>
  </div>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MyBlogApp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <p class="navbar-text float-right">
    <% if user_signed_in? %>
      Logged in as <strong><%= current_user.email %></strong>.
      <%= link_to "Edit profile", edit_user_registration_path, class: "navbar-link" %> |
      <%= button_to "Logout", destroy_user_session_path, method: :delete, class: "navbar-link"  %>
    <% else %>
      <%= link_to "Sign up", new_user_registration_path, class: "navbar-link"  %> |
      <%= link_to "Login", new_user_session_path, class: "navbar-link"  %>
    <% end %>
  </p>
    <%= yield %>


  </body>
</html>

app/views/shared/_header.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <div class="container-fluid">
    <a class="navbar-brand" href="#">Navbar</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item">
          <a class="nav-link active" aria-current="page" href="#">Home</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="#">Link</a>
        </li>
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
            Dropdown
          </a>
          <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
            <li><a class="dropdown-item" href="#">Action</a></li>
            <li><a class="dropdown-item" href="#">Another action</a></li>
            <li><hr class="dropdown-divider"></li>
            <li><a class="dropdown-item" href="#">Something else here</a></li>
          </ul>
        </li>
        <li class="nav-item">
          <a class="nav-link disabled" href="#" tabindex="-1" aria-disabled="true">Disabled</a>
        </li>
      </ul>
      <form class="d-flex">
        <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search">
        <button class="btn btn-outline-success" type="submit">Search</button>
      </form>
    </div>
  </div>
</nav>

app/views/users/shared/_error_messages.html.erb
<% if resource.errors.any? %>
  <div id="error_explanation" data-turbo-cache="false">
    <h2>
      <%= I18n.t("errors.messages.not_saved",
                 count: resource.errors.count,
                 resource: resource.class.model_name.human.downcase)
       %>
    </h2>
    <ul>
      <% resource.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/users/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= button_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider), data: { turbo: false } %><br />
  <% end %>
<% end %>